platform :ios, '11.0'
use_frameworks!

target 'MobileiaCore_Example' do
  pod 'MobileiaCore', :path => '../'

  target 'MobileiaCore_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
